MegaCinemaWeb/Areas/AdminDashboard/Controllers/CinemaController.cs
using MegaCinemaService;
using MegaCinemaWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MegaCinemaWeb.Infrastructure.Extensions;
using MegaCinemaModel.Models;
using MegaCinemaCommon.StatusCommon;
using AutoMapper;
using MegaCinemaWeb.Infrastructure.Core;

namespace MegaCinemaWeb.Areas.AdminDashboard.Controllers
{
    //[Authorize]
    public class CinemaController : BaseController
    {
        //TEST
        ICinemaService _cinemaService;
        IStatusService _statusService;
       
        IStaffService _staffService;


        public CinemaController(ICinemaService cinemaService, IStatusService statusService, IStaffService staffService)
        {
            _cinemaService = cinemaService;
            _statusService = statusService;
            _staffService = staffService;
        }

        // GET: AdminDashboard/Cinema
        public ActionResult Index(int page = 0)
        {   //Show List Cinema in Database
            int pageSize = CommonConstrants.PAGE_SIZE;
            int totalRow = 0;

            int count = _cinemaService.GetAll().OfType<Cinema>().Count();

            var result = _cinemaService.GetCinemaPaging(page, pageSize, out totalRow);
            var resultVm = Mapper.Map<IEnumerable<Cinema>, IEnumerable<CinemaViewModel>>(result);

            int totalPage = (int)Math.Ceiling((double)totalRow / pageSize);
            var paginationSet = new PaginationSet<CinemaViewModel>()
            {
                Items = resultVm,
                MaxPage = CommonConstrants.PAGE_SIZE,
                Page = page,
                TotalCount = totalRow,
                TotalPages = totalPage,
                Count = resultVm.Count(),
            };

            return View(paginationSet);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.CinemaStatus = new SelectList(_statusService.GetAll(), "StatusID", "StatusName");
            List<Staff> listStaff = (List<Staff>)_staffService.GetAll().Where(x => x.StaffStatus == "AC").ToList();

   
            ViewBag.CinemaManagerID = new SelectList(_staffService.GetAll(), "StaffID", "StaffCode");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CinemaViewModel cinemaViewModel)
        {
            if (ModelState.IsValid)
            {
                Cinema cinema = new Cinema();
                cinemaViewModel.CreatedDate = DateTime.Now;
                cinema.UpdateCinema(cinemaViewModel);

                if (cinema != null)
                {
                    _cinemaService.Add(cinema);
                    _cinemaService.SaveChanges();

                    //Redirect To Index Action
                    //SetAlert("Thêm rạp chiếu phim thành công!", CommonConstrants.SUCCESS_ALERT);
                    return RedirectToAction("Index");
                }
            }
            //Action/Controller
            ViewBag.CinemaStatus = new SelectList(_statusService.GetAll(), "StatusID", "StatusName");
            //ViewBag.StaffId = new SelectList(_staffService.GetAll(), "StaffID", "StaffCode");
            return View(cinemaViewModel);
        }


        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                Cinema cinema = _cinemaService.Find((int)id);
                _cinemaService.Delete(cinema);
                _cinemaService.SaveChanges();
            }

            return RedirectToAction("Index");
        }



        public ActionResult Edit(int? id)
        {
            CinemaViewModel cinemaViewModel = null;
            if (id != null)
            {
                Cinema cinema  = _cinemaService.Find((int)id);
                cinema.CinemaID = (int)id;
                cinemaViewModel = Mapper.Map<Cinema, CinemaViewModel>(cinema);
            }

            if (cinemaViewModel != null)
            {
                ViewBag.CinemaManagerID = new SelectList(_staffService.GetAll(), "StaffID", "StaffCode", cinemaViewModel.CinemaManagerID);
                ViewBag.CinemaStatus = new SelectList(_statusService.GetAll(), "StatusID", "StatusName", cinemaViewModel.CinemaStatus);
                return View(cinemaViewModel);
            }
               
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CinemaViewModel viewModel)
        {
            Cinema cinema = new Cinema();
            viewModel.UpdatedDate = DateTime.Now;
            cinema.UpdateCinema(viewModel);

            _cinemaService.Update(cinema);
            _cinemaService.SaveChanges();
         
            return RedirectToAction("Index");
        }
    }
}

MegaCinemaWeb/Areas/AdminDashboard/Views/Shared/_ConfirmBox.cshtml
<div class="modal fade" id=ConfirmModal tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="deleteLabel">Thông báo</h4>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn xóa dữ liệu hay không? </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Hủy</button>
                <button type="submit" class="btn btn-danger" id="deleteConfirm" url="" >Đồng ý</button>
            </div>
        </div>
    </div>
</div>

MegaCinemaWeb/Areas/AdminDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MegaCinemaWeb/Areas/AdminDashboard/Views/Shared/_LayoutPageAdmin.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../../Content/images/cinema_icon.ico" type="image/ico" size="16x16" />
    <title>@ViewBag.Title - Mega Cinema</title>

    <!-- Bootstrap -->
    <link href="~/Content/scripts/Admin/css/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/scripts/Admin/css/font-awesome/css/font-awesome.min.css" rel="stylesheet">  
    <!-- Custom Theme Style -->
    <link href="~/Content/scripts/Admin/css/custom-content.css" rel="stylesheet" />
    <link href="~/Content/scripts/Admin/css/custom.css" rel="stylesheet" />
    
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="#" class="site_title"><i class="fa fa-paw"></i> <span style="margin-left:10px">Mega Cinema!</span></a>
                    </div>
                    <div class="clearfix"></div>

                    <!-- menu profile quick info -->
                    <div class="profile">
                        @if (Request.IsAuthenticated)
                        {
                            <div class="profile_pic">
                                <img src="~/Content/images/background.png" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Xin chào,</span>
                                <h2>@User.Identity.GetUserName()</h2>
                            </div>
                        }
                        
                    </div>

                    <!-- /menu profile quick info -->

                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>Chức vụ</h3>
                            <!--Menu-->
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-home"></i>Thông tin rạp phim<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>
                                            @Html.ActionLink("Thêm rạp phim mới","Create","Cinema")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Danh sách rạp phim", "Index", "Cinema")
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-edit"></i>Phim <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Thêm thể loại phim", "Create", "FilmCategory")</li>
                                        <li>@Html.ActionLink("Danh sách thể loại phim", "Index", "FilmCategory")</li>
                                        <li>@Html.ActionLink("Thêm phim mới", "Create", "Film")</li>
                                        <li>@Html.ActionLink("Danh sách phim trong hệ thống", "Index", "Film")</li>
                                        <li>@Html.ActionLink("Dự đoán mức độ thành công của phim", "PreditionIndex", "Film")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-desktop"></i>Phòng chiếu <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>
                                            @Html.ActionLink("Thêm phòng chiếu phim", "CreateRoomDetail", "RoomFilm")
                                        </li>
                                        <li><a href="#">Danh sách phòng chiếu</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-table"></i>Combo kèm theo<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Thêm món ăn", "Create", "FoodList")</li>
                                        <li>@Html.ActionLink("Danh sách món ăn", "Index", "FoodList")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-clone"></i>Nhân viên <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Thêm nhân viên hệ thống", "StaffRegister", "Account")</li>
                                        <li>@Html.ActionLink("Danh sách nhân viên trong hệ thống", "Create", "FoodList")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-clone"></i>Ưu đãi <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Thêm ưu đãi mới", "Create", "Promotion")</li>
                                        <li>@Html.ActionLink("Danh sách ưu đãi", "Index", "Promotion")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-clone"></i>Phòng vé <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>@Html.ActionLink("Thống kê vé", "Index", "BookingTicket")</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle" href="javascript:void(0)" ><i class="fa fa-bars"></i></a>
                        </div>
                        @Html.Partial("_LoginPartial")
                        @*<ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="~/Content/images/background.png" alt="..."> Phạm Phú
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="#" id="btnPasswordChange"> Thay đổi mật khẩu</a></li>
                                    <li><a href="#"><i class="fa fa-sign-out pull-right"></i> Đăng xuất</a></li>
                                </ul>
                            </li>
                        </ul>*@
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->

            <!--Modal pop up Detail-->
            <div class="modal fade" id="PasswordChange" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" style="text-transform:uppercase">Thay đổi mật khẩu</h4>
                        </div>
                        <div class="modal-body">
                            <!--content of submit form -->
                            <form>
                                <div class="form-group">
                                    <label for="txtEmailUser">Mật khẩu cũ: </label>
                                    <input type="password" class="form-control" id="txtOldPassword" autocomplete="off">
                                </div>
                                <div class="form-group">
                                    <label for="txtEmailUser">Mật khẩu mới</label>
                                    <input type="password" class="form-control" id="txtNewPassword1" autocomplete="off">
                                </div>
                                <div class="form-group">
                                    <label for="txtEmailUser">Nhập lại mật khẩu mới</label>
                                    <input type="password" class="form-control" id="txtNewPassword2" autocomplete="off">
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary" id="btnSavePassWord">Save</button>
                        </div>
                        <div id="AlertBoxChange" class="alert alert-success" style="margin-left:10px; margin-right:10px">Thành Công</div>
                    </div>
                </div>
            </div>

            <!-- page content -->
            <div class="right_col" role="main">
                <!-- top tiles -->
                <div class="row tile_count">
                    <p class="feature-title text-center">@ViewBag.FeatureTitle</p>
                </div>
                <!-- /top tiles -->
                <br />
                <div class="row feature-main-content">
                    @if (TempData["AlertMessage"] != null)
                    {
                        <div id="alert-custombox" class="alert @TempData["AlertType"] hide">
                            @TempData["AlertMessage"]
                        </div>
                    }
                    @RenderBody()
                </div>

            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    Mega Cinema Dashboard <a href="https://www.facebook.com/groups/570466236321946/?fref=ts">Uboiz Team</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <!-- jQuery -->
    <script src="~/Content/scripts/Admin/js/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/scripts/Admin/css/bootstrap/dist/js/bootstrap.min.js"></script>

    <script src="~/Content/scripts/Admin/js/custom.min.js"></script>
    <script src="~/scripts/adminjs.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

MegaCinemaWeb/Areas/AdminDashboard/Views/Shared/_bookingAlert.cshtml
<div class="modal fade" id=ConfirmModal tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="deleteLabel">Thông báo</h4>
            </div>
            <div class="modal-body">
                <p>Bạn đã thực hiện thao tác quá số lần quy định !</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Đồng ý</button>
            </div>
        </div>
    </div>
</div>